### ISSUE TITLE
Error message when opening a norg file

### ISSUE THREAD

**Issue by kishikaisei** [vhyrro/neorg#33]
For some reason when opening a norg file, either by `nvim name.norg` or inside nvim `:e name.norg` I get this:
![neorg](https://user-images.githubusercontent.com/1894123/127153230-5029473f-d424-469d-8cc5-98858b4baf30.png)
That message does not appear when opening the file through `telescope,nvim` though.
The error is skippable, and does not seem to have any effect.

**Comment by vhyrro** [comment]
I think I might know what the issue is, but can you answer 2 questions real quick?
a) What OS are you running?
b) Are you running the `unstable` branch or the regular `main` version of Neorg?

**Comment by kishikaisei** [comment]
a) Windows 11 (21996.1)
b) `unstable`

**Comment by vhyrro** [comment]
Aha, just as I thought :P

The automatic tag generator is attempting to get the current windows machine's username to place in as the author, but I never tested the code on windows since I don't have a windows machine and it seems to not be grabbing the username properly. This shouldn't be a difficult fix, I'll let you know when it's patched up and when it works

**Comment by vhyrro** [comment]
I spun up a Windows VM real quick and tested the code and it seems to work as intended now, mind updating and giving it a shot?

**Comment by kishikaisei** [comment]
Damn man, you work fast 😆 
It's flawless now so closing.
