### ISSUE TITLE
[BUG] Incorrect icon rendering

### ISSUE THREAD

**Issue by vuki656** [vhyrro/neorg#45]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the latest neovim version (0.5)

### Neovim Version

NVIM v0.6.0-dev+8-g75f758b99

### Log Output

N/A

### Branch

unstable

### Loaded modules

```lua
neorg.setup({
    load = {
        ["core.defaults"] = {},
        ["core.norg.concealer"] = {},
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    my_workspace = "~/notes",
                },
            },
        },
        ["core.keybinds"] = {
            config = {
                default_keybinds = true,
                neorg_leader = "<Leader>o",
            },
        },
    },
})
```

### Expected behavior

When I type in `**` for it to render the icon instead of the broken icon.

### Actual behavior

When I type in `**` (or and other * combos, haven't tested with other icons), it renders this

![image](https://user-images.githubusercontent.com/8104698/127719791-a19fec2b-549d-4302-a192-f5f63f759cb5.png)

If I remove space at the start of the line it fixes it.

What I noticed happens, is if I'm at the beginning of the line, and type in `**` it's going to insert a space before those characters and render the bugged-out icon. If I remove the space it inserts at the start of the line it fixes it.

### Help

No

**Comment by vhyrro** [comment]
This is particularly odd, I can't seem to replicate this in any way (nor have I heard complaints from others too much regarding this).

Could you try recompiling and updating Neovim plz? I have a feeling a lot of those issues could be because of that. Extmarks and stuff might have gotten updates since then, idk.

**Comment by vhyrro** [comment]
It could potentially be some sort of desync between both core.norg.esupports and core.norg.concealer, but i have no idea how that would play into anything since they're pretty independent and shouldn't affect the line number the icon is placed on

I'm gonna try taking some shots in the dark later on, maybe get them to synchronize with each other a bit better

**Comment by vuki656** [comment]
Bumping neovim to the latest and recompiling plugins seems to have fixed it. Thanks.

**Comment by vhyrro** [comment]
Ah, that's great to hear 😅. Glad it works now!
