### ISSUE TITLE
Code Blocks

### ISSUE THREAD

**Issue by David-Kunz** [vhyrro/neorg#7]
Hi,

This is a feature request to make code blocks a bit nicer to use.

### Current State
```
@code javascript
  const foo = () => { console.log('hello world') }
@end
```

### Proposal 1
Have the same identifiers as in GitHub markdown, e.g.
```
@code js
  const foo = () => { console.log('hello world') }
@end
```

### Proposal 2
Also allow triple backticks, e.g.
```
| ```js
|   const foo = () => { console.log('hello world') }
| ```
```

**Comment by vhyrro** [comment]
Hm, this is where we hit a few roadblocks:
a) The `js` language is actually supported (it's available in the autocompletion menu as you type) however it's treesitter that actually handles injecting itself (and syntax highlighting) into code blocks. All I do is tell TreeSitter "hey, this part of the syntax tree is the name of the language to inject" and TS handles the rest. It seems that `js`is not recognized by TreeSitter as a language to inject, but `javascript` is. I think there may be a way to change this behaviour with some special queries, I will see whether there's anything online, because from my current attempts an incredible 0 of them worked
b) Even though the first problem may be solvable, I don't think that the second one is possible. We actually purposefully decided against triple backticks for code blocks as a design choice. This is for two reasons. The first is that triple backticks would instantly break all defined rules regarding modifiers. Modifiers simply cannot span longer than a single paragraph, alongside a few other things. The second is because of the annoyances that come with triple backticks, like this:
Hello, this is a \`\`\`
code block
\`\`\` and here I keep writing.
Or:
\- Here's some code that you should read: \`\`\`
   <the code>
   \`\`\` - description

This hinders readability and just all round looks worse in my opinion. Even markdown itself doesn't know how to handle these situations at times, hah

I will look into the TreeSitter stuff when I get the time though and I'll let you know of any findings.

**Comment by David-Kunz** [comment]
Hi @vhyrro ,

Thanks a lot for your extensive answer!  Not supporting backticks is fine for me, it was just a suggestion as many people are already used to that.

Thanks and best regards,
David

**Comment by vhyrro** [comment]
Hey, I fixed the problem. The `js` shorthand now shows javascript syntax highlighting (at least from my tests). The issue is that this process will probably have to be done for a lot of different languages with their own shorthands. This is a message to all people: if a shorthand for your language doesn't work, then please let me know in an issue. Fixing the problem is rather trivial and requires little work.

**Comment by David-Kunz** [comment]
Awesome, thanks a lot for this quick fix @vhyrro !
