### ISSUE TITLE
[BUG] Treesitter highlighting does not work for latex code blocks

### ISSUE THREAD

**Issue by SCJangra** [vhyrro/neorg#97]
### Neovim Version

NVIM v0.6.0-dev+nightly-3-g384a43fe7
Build type: Release
LuaJIT 2.1.0-beta3
Features: +acl +iconv +tui

### Branch

unstable

### Loaded modules

```
core.defaults
core.norg.concealer
core.integrations.telescope
core.norg.completion
core.norg.dirman
```

### Expected behavior

Latex code highlighting should be the same as a normal .tex file.

### Actual behavior

Latex code is not highlighted at all.

### Other information

Highlighting in Neorg
![image](https://user-images.githubusercontent.com/40860699/132453267-7ce11d3f-20c1-41bc-8f54-6599982a7a03.png)

Highlighting in .tex file
![image](https://user-images.githubusercontent.com/40860699/132453357-ec1f0c04-0f99-4e58-8e53-32f55e071795.png)

Treesitter Playground shows some errors.
![image](https://user-images.githubusercontent.com/40860699/132453490-23fccb9f-1046-4f58-a31d-8864edf9dee9.png)

**Comment by vhyrro** [comment]
Hey man! That treesitter AST screenshot made the fix so much easier lol, thx for saving me a few hours.

It should be fixed now both in `unstable` and in `main` so please update your plugin. Also update the treesitter parser because I fixed an issue there too. I've also changed the completion to now only contain languages that have highlighting support OOTB rather than just listing pretty much all languages in existence. You should use:

```
@code latex
\latex{stuff}
@end
```

Now so treesitter can catch it and provide `latex` highlights :)

**Comment by SCJangra** [comment]
@vhyrro Cool, i've updated the plugin and treesitter parser and everything seems to be working fine, so I should close this now.

BTW how do you know I am a man? (lol!, just a jock)

**Comment by vhyrro** [comment]
I just call everyone "man" or "dude" by default lol 😄

**Comment by Galicarnax** [comment]
Having exactly the same issue with the latest versions of plugins. `tex` and `latex` block quotes are not identified as injections by treesitter (or identified, but injected content is `norg` again). In
```norg
@code latex
\latex{stuff}
@end
```
`stuff` is also identified as `norg`, not `latex`.

**Comment by Galicarnax** [comment]
Never mind... 🙄 It escaped my attention that treesitter parser for `latex` was missing on that host
